@startuml
class Користувач{
запит
}
class Профіль{
ПІБ
..
Login
..
Email
..
Password
..
Контактні дані
..
}

class Аутентифікація{
Login
..
Email
..
Password
..
}

class Права{
Статус
..
інше
..
}

class Документ{

Назва
..
Шлях
..
Тип
..
Теги
..
Посилання
..
інше
..
}

class Дії{
+Пошук
запит
+Завантажити
шлях
..
+Оновити
назва
оновлення
..
+Переглянути вміст
назва
..
+Видалити
назва
шлях
..
+Додати тег
назва
шлях
тег(и)
..
}
class Статус{
статус дії
..
}


Профіль "[1,1]" -left.. "[1,1]" Аутентифікація
Користувач -down--> (Профіль, Аутентифікація)
Профіль "[1,1]" -left.. "[1,1]" Права
Профіль "[0,*]" -down--> "[1,*]" Документ
Документ "[1,*]" -right--> "[1,1]" Дії
Дії "[0,1]" -right.. "[1,1]" Статус


@enduml